import { test, expect } from '@playwright/test';
import { readFile } from 'node:fs/promises';

test('expense creation, chart/list colors, persistence, Sunday report, download and deletion', async ({ page, request }) => {
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  // This dedicated test server uses test-results/e2e-expenses.json, never real user data.
  const existing = await (await request.get('/api/expenses')).json();
  for (const expense of existing) await request.delete(`/api/expenses/${expense.id}`);
  await page.goto('/');
  await expect(page.getByText('A fresh start for your week')).toBeVisible();
  await page.getByLabel('What was it for?').fill('Coffee with friends');
  await page.getByLabel('Amount', { exact: true }).fill('12.50');
  await page.getByLabel('Date', { exact: true }).fill('2026-09-17');
  await page.getByLabel('A little context').fill('Study break');
  await page.getByRole('button', { name: 'Save expense' }).click();
  await expect(page.getByRole('cell', { name: '17/sep/26 thursday' })).toBeVisible();
  await expect(page.getByRole('cell', { name: '$12.50', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Edit Coffee with friends' }).click();
  await expect(page.getByLabel('What was it for?')).toHaveValue('Coffee with friends');
  await page.getByLabel('Amount', { exact: true }).fill('99');
  await page.getByRole('button', { name: 'Cancel editing' }).click();
  await expect(page.getByRole('cell', { name: '$12.50', exact: true })).toBeVisible();
  await expect(page.getByText('Study break', { exact: true })).toBeVisible();
  await expect(page.locator('.expense-table .category-dot')).toHaveCSS('background-color', 'rgb(234, 170, 67)');
  await expect(page.locator('.recharts-pie-sector path').first()).toHaveAttribute('fill', '#eaaa43');
  await page.reload();
  await page.getByLabel('Choose a date in the report week').fill('2026-09-17');
  await expect(page.getByRole('cell', { name: '$12.50', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Edit Coffee with friends' }).click();
  await page.getByLabel('What was it for?').fill('Metro estación');
  await page.getByLabel('Amount', { exact: true }).fill('15.75');
  await page.getByLabel('Date', { exact: true }).fill('2026-09-18');
  await page.getByLabel('Category', { exact: true }).selectOption('auto');
  await page.getByLabel('A little context').fill('Transporte a la universidad. Café después.');
  await page.getByRole('button', { name: 'Save changes' }).click();
  await expect(page.getByRole('cell', { name: '$15.75', exact: true })).toBeVisible();
  await expect(page.getByRole('cell', { name: '18/sep/26 friday' })).toBeVisible();
  await expect(page.locator('.expense-table .category-dot')).toHaveCSS('background-color', 'rgb(104, 155, 138)');
  await page.getByRole('button', { name: 'Switch to dark mode' }).click();
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark');
  await page.reload();
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark');
  await page.getByLabel('Choose a date in the report week').fill('2026-09-17');
  await expect(page.getByRole('cell', { name: '$15.75', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Weekly report', exact: true }).click();
  await page.getByRole('button', { name: 'Simulate Sunday report' }).click();
  await expect(page.getByText('Report generated for Sunday, Sep 20.')).toBeVisible();
  await expect(page.locator('.daily-row')).toHaveCount(7);
  await expect(page.locator('.report-total')).toContainText('$15.75');
  await expect(page.getByRole('region', { name: 'Expenses for 2026-09-18' })).toContainText('Metro estación');
  await expect(page.getByRole('region', { name: 'Expenses for 2026-09-18' })).toContainText('Transporte a la universidad. Café después.');
  await page.evaluate(() => window.scrollTo(0, 0));
  await page.screenshot({ path: 'test-results/report-dark.png', fullPage: true });
  const downloadPromise = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Download report (.pdf)' }).click();
  const download = await downloadPromise;
  expect(download.suggestedFilename()).toBe('penny-weekly-2026-09-20.pdf');
  await download.saveAs('test-results/weekly-report.pdf');
  expect((await readFile('test-results/weekly-report.pdf')).subarray(0, 5).toString()).toBe('%PDF-');
  await page.getByRole('button', { name: 'Overview', exact: true }).click();
  await page.getByLabel('Search expenses').fill('not present');
  await expect(page.getByText('No matching expenses', { exact: true })).toBeVisible();
  await page.getByLabel('Search expenses').fill('');
  await page.getByRole('button', { name: 'Delete Metro estación' }).click();
  await page.getByRole('button', { name: 'Delete expense', exact: true }).click();
  await expect(page.getByText('A fresh start for your week')).toBeVisible();
  await page.getByRole('button', { name: 'Load sample week' }).click();
  await expect(page.locator('.expense-table tbody tr')).toHaveCount(8);
  await page.evaluate(() => window.scrollTo(0, 0));
  await page.screenshot({ path: 'test-results/dashboard-dark.png', fullPage: true });
  await page.getByRole('button', { name: 'Switch to light mode' }).click();
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'light');
  await page.screenshot({ path: 'test-results/dashboard-desktop.png', fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  await expect(page.getByRole('button', { name: 'Save expense' })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.screenshot({ path: 'test-results/dashboard-mobile.png', fullPage: true });
  await page.getByRole('button', { name: 'Switch to dark mode' }).click();
  await expect(page.locator('.nav-item.active')).toHaveCSS('background-color', 'rgb(41, 60, 85)');
  await page.screenshot({ path: 'test-results/dashboard-mobile-dark.png', fullPage: true });
  expect(errors).toEqual([]);
});

test('PDF handles empty days and long notes across multiple pages', async ({ page, request }) => {
  const existing = await (await request.get('/api/expenses')).json();
  for (const expense of existing) await request.delete(`/api/expenses/${expense.id}`);
  await page.goto('/');
  await page.getByLabel('Choose a date in the report week').fill('2026-09-17');
  await page.getByRole('button', { name: 'Weekly report', exact: true }).click();
  await expect(page.locator('.day-empty')).toHaveCount(7);
  const emptyDownload = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Download report (.pdf)' }).click();
  await (await emptyDownload).saveAs('test-results/empty-report.pdf');
  for (let index = 0; index < 18; index++) {
    const reason = index === 0 ? 'Línea\n'.repeat(79) + 'FINAL DE NOTA' : 'Descripción larga para comprobar el salto de página y la lectura de cada nota. '.repeat(6);
    const response = await request.post('/api/expenses', { data: { concept: `Expense ${index + 1} - Café y educación`, amount: '10.01', date: '2026-09-17', reason, category: 'food' } });
    expect(response.status()).toBe(201);
  }
  await page.getByRole('button', { name: 'Simulate Sunday report' }).click();
  await expect(page.locator('.daily-expenses li')).toHaveCount(18);
  await expect(page.locator('.report-total')).toContainText('$180.18');
  const longDownload = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Download report (.pdf)' }).click();
  await (await longDownload).saveAs('test-results/long-report.pdf');
});
