import { Pencil, ReceiptText, Search, Trash2 } from 'lucide-react';
import { money } from '../utils.js';

export default function ExpenseList({ expenses, search, onSearch, onDelete, onEdit, busy }) {
  const visible = expenses.filter(expense => `${expense.concept} ${expense.reason} ${expense.categoryLabel}`.toLowerCase().includes(search.toLowerCase()));
  return <section className="panel list-panel" aria-labelledby="expenses-heading">
    <div className="list-heading"><div className="flex items-center gap-2"><h2 id="expenses-heading">Tus gastos</h2><span className="count-badge">{expenses.length}</span></div><div className="search-input"><Search size={15} /><input aria-label="Buscar gastos" placeholder="Buscar un gasto…" value={search} onChange={event => onSearch(event.target.value)} /></div></div>
    {visible.length ? <div className="expense-table-wrap"><table className="expense-table"><thead><tr><th>GASTO</th><th>FECHA</th><th className="text-right">IMPORTE</th><th><span className="sr-only">Acciones</span></th></tr></thead><tbody>{visible.map(expense => <tr key={expense.id}><td><div className="flex items-start gap-3"><span className="category-dot mt-1.5 shrink-0" style={{ backgroundColor: expense.color }} /><div><strong>{expense.concept}</strong><span className="expense-category">{expense.categoryLabel}</span>{expense.reason && <p className="expense-reason">{expense.reason}</p>}</div></div></td><td><time dateTime={expense.date}>{expense.formattedDate}</time></td><td className="text-right font-semibold whitespace-nowrap">{money(expense.amountCents)}</td><td><div className="expense-actions"><button type="button" className="edit-button" onClick={() => onEdit(expense)} disabled={busy} aria-label={`Editar ${expense.concept}`} title="Editar gasto"><Pencil size={15} /></button><button type="button" className="delete-button" onClick={() => onDelete(expense)} disabled={busy} aria-label={`Eliminar ${expense.concept}`} title="Eliminar gasto"><Trash2 size={15} /></button></div></td></tr>)}</tbody></table></div> : <div className="empty-list"><ReceiptText size={25} /><strong>{search ? 'No hay gastos que coincidan' : 'Una semana por comenzar'}</strong><p>{search ? 'Prueba con otro concepto, categoría o nota.' : 'Agrega un gasto o carga una semana de ejemplo.'}</p></div>}
    <div className="list-footer">{visible.length} de {expenses.length} gastos <span>Importes en MXN</span></div>
  </section>;
}
