import { Pencil, ReceiptText, Search, Trash2 } from 'lucide-react';
import { money } from '../utils.js';

export default function ExpenseList({ expenses, search, onSearch, onDelete, onEdit, busy }) {
  const visible = expenses.filter(expense => `${expense.concept} ${expense.reason} ${expense.categoryLabel}`.toLowerCase().includes(search.toLowerCase()));
  return <section className="panel list-panel" aria-labelledby="expenses-heading">
    <div className="list-heading"><div className="flex items-center gap-2"><h2 id="expenses-heading">Your expenses</h2><span className="count-badge">{expenses.length}</span></div><div className="search-input"><Search size={15} /><input aria-label="Search expenses" placeholder="Find an expense…" value={search} onChange={event => onSearch(event.target.value)} /></div></div>
    {visible.length ? <div className="expense-table-wrap"><table className="expense-table"><thead><tr><th>EXPENSE</th><th>DATE</th><th className="text-right">AMOUNT</th><th><span className="sr-only">Actions</span></th></tr></thead><tbody>{visible.map(expense => <tr key={expense.id}><td><div className="flex items-start gap-3"><span className="category-dot mt-1.5 shrink-0" style={{ backgroundColor: expense.color }} /><div><strong>{expense.concept}</strong><span className="expense-category">{expense.categoryLabel}</span>{expense.reason && <p className="expense-reason">{expense.reason}</p>}</div></div></td><td><time dateTime={expense.date}>{expense.formattedDate}</time></td><td className="text-right font-semibold whitespace-nowrap">{money(expense.amountCents)}</td><td><div className="expense-actions"><button type="button" className="edit-button" onClick={() => onEdit(expense)} disabled={busy} aria-label={`Edit ${expense.concept}`} title="Edit expense"><Pencil size={15} /></button><button type="button" className="delete-button" onClick={() => onDelete(expense)} disabled={busy} aria-label={`Delete ${expense.concept}`} title="Delete expense"><Trash2 size={15} /></button></div></td></tr>)}</tbody></table></div> : <div className="empty-list"><ReceiptText size={25} /><strong>{search ? 'No matching expenses' : 'A fresh start for your week'}</strong><p>{search ? 'Try a different name, category, or note.' : 'Add an expense using the form, or explore with sample data.'}</p></div>}
    <div className="list-footer">{visible.length} of {expenses.length} expenses <span>All amounts in USD</span></div>
  </section>;
}
